apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-app
  namespace: default
spec:
  dnsNames:
    - martyniuk-devops.ml
  secretName: test-app
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer