apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: martyniukighor@gmail.com
    privateKeySecretRef:
      name: test-app
    solvers:
    - http01:
       ingress:
         class: nginx